### ISSUE TITLE
Profvis isn't launching the html widget

### ISSUE THREAD

**Issue by john-james-sf** [rstudio/profvis#92] opened 2018-02-04 23:02 UTC
Hi,

I'm running the following in Rstudio v. 1.1.419
library(profvis)
profvis({
  testReallyHazardousStuff()
})
The indicator says that it is profiling, but no html page or viewer launches.  I've reinstalled R and profvis, but no luck.  Please advise.

**Comment by wch** [comment] 2018-02-05 06:22
I'm not able to reproduce this on my Mac.

![image](https://user-images.githubusercontent.com/86978/35790842-470d8d68-09f9-11e8-89f7-8db9fcb027e7.png)


Can you include the output of `devtools::session_info()`?

**Comment by DataScienceSalon** [comment] 2018-02-05 08:10
Thanks Winston!  Hope you can see this.  
![screenshot 2](https://user-images.githubusercontent.com/20120789/35794038-0bcd5700-0a22-11e8-8128-ab38c9c2a085.png)

**Comment by lionel-** [comment] 2020-11-16 17:07
Closing this as the issue is now more than 2 years old. If you still have this problem with recent R, RStudio, and packages, please post a reprex.

**Closed by lionel-** 2020-11-16 17:07 UTC
