### ISSUE TITLE
profvis: [WARNING] This document format requires a nonempty <title> element.

### ISSUE THREAD

**Issue by leandroroser** [rstudio/profvis#90] opened 2017-11-13 19:27 UTC
Hi, 

I am trying to use profvis after updating RStudio, and I get this error message:

  _[WARNING] This document format requires a nonempty <title> element.
   Please specify either 'title' or 'pagetitle' in the metadata.
   Falling back to 'file2d443c0001b0'_

I have tried with the following example, but I also have the error message and no output:

#---------------------#
library(profvis)

profvis({
  data(diamonds, package = "ggplot2")
  
  plot(price ~ carat, data = diamonds)
  m <- lm(price ~ carat, data = diamonds)
  abline(m, col = "red")
})
#--------------------#

Do you know what could be causing this problem?

Thanks,

**Comment by wch** [comment] 2017-11-14 15:57
Which version of RStudio are you using?

**Comment by leandroroser** [comment] 2017-11-14 17:01
I am using RStudio 1.1.371-1, in a Linux system (Archlinux).  I have installed the package from the AUR repository: https://aur.archlinux.org/packages/rstudio-desktop-git/. Could it be a problem related with this repo?

**Comment by wch** [comment] 2017-11-14 17:40
It works fine with 1.1.383 on my Mac.

I believe that the problem is due to this: ramnathv/htmlwidgets#289

**Comment by leandroroser** [comment] 2017-11-14 18:45
Thanks! Now is working with 1.1.383.

**Comment by wch** [comment] 2017-11-14 19:22
Closing this issue because the problem is due to htmlwidgets.

**Closed by wch** 2017-11-14 19:22 UTC
