### ISSUE TITLE
pandoc.exe: Out of memory

### ISSUE THREAD

**Issue by VT-SCM** [rstudio/profvis#89] opened 2017-11-08 16:17 UTC
This issue has been asked but I'd like to have it emerged since it doesn't look like an uncommon issue. 
    profvis({runApp("Path_To_App", display.mode = "normal")})

The app takes a few hundred MB memory, but pandoc.exe takes more and more memory until a point it crashed due to the 2GB memory limit.

Is there a solution to this? Why does pandoc.exe take so much memory?
Thanks,
Victor

**Comment by wch** [comment] 2018-02-22 15:24
The memory usage is probably due to jgm/pandoc#3169. I don't know of a workaround at this point.

**Comment by lionel-** [comment] 2020-11-17 10:08
Duplicate of #67.

**Closed by lionel-** 2020-11-17 10:08 UTC
Labels: performance
